### ISSUE TITLE
push button and led for Jetson Xavier running ubuntu

### ISSUE THREAD

**Issue by CDDevel** [perimeno/LIO#5]
Hi,

Can this be used to add a push button (input) and a led (output) to a Jetson Xavier GPIO using c++? 

(tried to label as question rather than issue but don't know how sorry)

thanks

**Comment by ssi-hu-laszlo-vitez** [comment]
Hi,

NP.:)

Sorry, but I can't get your question properly, because I didn't know anything about Jetson before. If you would like to handle GPIO ports via LIO's interface there should be an implementation that is based on Jetson. Or you would like to use this library to drive IOs with the implementation for sysFs? It is possible to drive any kind of gpio in linux as far as it is mapped to sysfs.
If it is not (sysfs becomes obsolete, so it is possible today's technology is not based on this solution) you can give a try for GPOIlib implementation and try to access to the proper chip, but this implementation has some bug, so it is possible that you couldn't use it either. 

L

**Comment by ssi-hu-laszlo-vitez** [comment]
ahhnh, now I am getting closer:D so Jetson is a board that is made by nVidia, and you are running Ubuntu Xavier on it. 
It is higly possible that you could use this library, as I mentioned before as far as GPIO ports are mapped tot sysFS on OS level, you can use LIO to access to them. Keep in mind you need to have proper rights for the user that runs LIO to be able to access GPIO pins. I.e. be part of GPIO group or something else. 

Unfortunately I don't own Jetson board, so I can't give a try. :(

**Comment by CDDevel** [comment]
I'm using gpio422 for the output led and gpio428 for the input button (pulled high to activate)

these are both sysfs.

if I insert these into the example code will I be able to test? 

I can see that there is a section in the example code which changes the state of the output pins but I can't see a test for input? i'm looking for a "if input pin goes high then print hello world"kind of test haha

Sorry these are beginner questions I know

thanks for help!

c

**Comment by ssi-hu-laszlo-vitez** [comment]
You can set the input pin number at line 71. The input pin waits for events asynchronously. The example code conontains a debouncing component attached to the raw pin, and you can set callback for 0->1 and 1->0 transitions at line 87-88. So you can modify the body for these function(```DebouncedOnEvent```, ```DebouncedOffEvent```) to do whatever you want. 
Please not the example code activates the internal pull-down resistors, so you should set it to ```highZ``` or ```PullUp``` at line 78.

**Comment by CDDevel** [comment]
thanks!

I have built a circuit board so want to use external resistors does this make any difference? (I'm a circuit board engineer rather than software hence the simple questions)

just to confirm do I need to change lines 87-88 to set callback? or is this already set in the example?
I simply want some indication the input is seen, whatever that maybe, (on my PI software it just print 1 or 0 in terminal)

cheers

**Comment by ssi-hu-laszlo-vitez** [comment]
If you are going to use external resistors, I would set input pin to HiZ. 78: ```in_pin_sysfs->SetPullUpDown(InputPin::PullUpDown::PullDown);```->```in_pin_sysfs->SetPullUpDown(InputPin::PullUpDown::HiZ);```
You do not need to modify line 87-88, the callbacks are already set, just put your logic into the body L41 for 0->1 event, and L47 for 1->0.

btw if you would like to just see the input is working or not, the callbacks in the example print text into the stdout in case of the input changed.

**Comment by CDDevel** [comment]
thanks for your help! much appreciated :)

**Comment by perimeno** [comment]
Can you managed to make input port work as well?
